### ISSUE TITLE
Doesn't work on 1.16.5

### ISSUE THREAD

**Issue by Bloodlex** [bobby29831/SpartanWebhooks#1]
Hey,

Is it possible to make this work also for 1.16.5?

Thanks a lot!

**Comment by bobby29831** [comment]
I figured it would because of no issues from testing it on 1.12.2 and 1.8.8, and developing it natively on 1.17.1

I don't imagine there should be any issues with 1.16.5, but I can test and solve any issues later today. If you have a particular startup error that would be very helpful.

**Comment by bobby29831** [comment]
This is fixed on the latest Spigot update (1.1.2)
