### ISSUE TITLE
Java version

### ISSUE THREAD

**Issue by CryLegende** [bobby29831/SpartanWebhooks#2]
Hello, the plugin was compiled in a recent version of java so it can't work on older versions of the game (1.7 -> 1.12)

`org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: dev/arrow/spartanaddon/SpartanWebhooks has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0`

thank you for your help

**Comment by bobby29831** [comment]
Forgot to tweak this — apologies! I’ll fix this as soon as I’m available to!

**Comment by CryLegende** [comment]
Thank you ! ^^

**Comment by bobby29831** [comment]
This should be resolved in the latest spigot update (1.1.4)
