### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by Yousa715** [bobby29831/SpartanWebhooks#3]
ii get this error a lot of times when the AC send a lot of alerts 

[19:17:34 ERROR]: [dev.arrow.spartanaddon.libs.discord.webhook.WebhookClient] Encountered 429, retrying after 3108000 ms

**Comment by bobby29831** [comment]
What version of the plugin are you running? Make sure to be on the latest because there have been lots of stability updates.

**Comment by bobby29831** [comment]
c81d5a52f5218dbfcf64573d67c937e5d2c23f33 should fix this issue, or at least reduce it.
